### ISSUE TITLE
Add New Emojis with Appropriate Function Names

### ISSUE THREAD

**Issue by mubaris** [gostudent/console#1]

**Comment by GOVINDDIXIT** [comment]
I will do this

**Comment by gauthamzz** [comment]
ok do it

**Comment by mubaris** [comment]
- [ ] :warning:
- [ ] :hamburger:
- [ ] :crown:
- [ ] :art:
- [ ] :bomb:
- [ ] :octopus:
- [ ] :snake:
- [ ] :panda_face:
- [ ] :cat:
- [ ] :trollface:
- [ ] :zap:
- [ ] :exclamation:
- [ ] :question:
- [ ] :heart:

**Comment by mubaris** [comment]
If you're working on this, add above emojis

**Comment by pani-vishal** [comment]
Are all the emojis added? If not i can do so.

**Comment by mubaris** [comment]
Add the emojis in the list

**Comment by pani-vishal** [comment]
Sure will do!

**Comment by gaurav-gogia** [comment]
Hi!

Can I work on a similar issue of adding more emojis? 

Thanks, 🙂

**Comment by gauthamzz** [comment]
Yeah
